### ISSUE TITLE
Global Box Sizing

### ISSUE THREAD

**Issue by ahenriksen-fedx** [Esri/esri-eds#300]
Change the `styles.css` and set the `box-sizing` to `border-box` and the `padding` to `0`. Example:

```css
*,
*::before,
*::after {
	box-sizing: border-box;
	border: 0;
}
```
